name: spotify-build
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - flask=*
  - jinja2=*
  - flask-sqlalchemy=*
  - python-dotenv=*
  - scikit-learn=*
  - gunicorn=*
  - requests=*
  - spotipy=*
  - pandas=*
  - numpy=*
  - dill=*